#!/bin/sh
INTERFACE="/dev/$(/usr/bin/head -1 /etc/ppp/options-mobile)"
for ((retry=0; retry < 40; retry++))
do
    if [ -c ${INTERFACE} ]; then
        /usr/bin/logger "$0: OK existing required device ${INTERFACE} (in $((retry / 4)).$((100 * (retry % 4) / 4)) seconds)"
        break
    else
        /bin/sleep 0.25
    fi
done
if [ ! -c ${INTERFACE} ]; then
    /usr/bin/logger "$0: ERROR timeout waiting for required device ${INTERFACE}"
fi
exit 0
